name: Bug Fix
description: A bug has been fixed
labels:
  - "bug"
body:
  - type: input
    id: issues
    attributes:
      label: Issue(s) Fixed
      description: Please list all issues that are fixed in this pull request
      value: Fixes #
    validations:
      required: true
  - type: textarea
    id: summary
    attributes:
      label: Summary of Fix
      description: Please give a brief description of the fix applied
    validations:
      required: true
