- name: blocked
  description: This issue blocked by another issue

- name: bug
  description: Something isn't working

- name: design
  description: design and visual

- name: dev
  description: Related to the development enviornment

- name: documentation
  description: Improvements or additions to documentation

- name: duplicate
  description: This issue or pull request already exists

- name: enchancement
  description: New feature, enchancement, or request

- name: feedback requested

- name: good first issue
  description: Good for newcomers

- name: help wanted
  description: Extra attention is needed

- name: in progress
  description: Currently being worked on

- name: infrastructure
  description: Related to infrastructure

- name: invalid
  description: This doesn't seem right

- name: JB - action needed
  description: action needed from a JB Team member

- name: JB - need decision
  description: decision/consult needed from JB Team

- name: low priority

- name: meta-issue
  description: Add to issue that has sub-tasks/issues (check list in the description of other issues)

- name: question
  description: Further information is requested

- name: show notes

- name: show-scraper
  description: Issues related to the https://github.com/JupiterBroadcasting/show-scraper project

- name: third-party site

- name: urgent

- name: UX
  description: Related to User Expirence

- name: wontfix
  description: This will not be worked on
