name: Bug Report
description: File a bug report
labels:
  - "bug"
body:
  - type: input
    id: address
    attributes:
      label: URL
      description: URL where the bug was found
      placeholder: https://jupiterbroadcasting.com/
  - type: dropdown
    id: devices
    attributes:
      label: What devices did you see this bug on?
      multiple: true
      options:
        - Phone
        - Tablet
        - Desktop
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Describe the bug you encountered
    validations:
      required: true
