name: Website Bug Report
description: For problems with the design or functionality of the website.
labels:
  - "bug"
  - "design"
body:
  - type: markdown
    attributes:
      value: |
        #### Thank you for reporting a bug! Please provide any information you think can help. Screenshots are a great help as well!
        ### Also please check to see if someone else has already reported this bug.
  - type: input
    id: address
    attributes:
      label: URL
      description: URL where the bug was found
      placeholder: https://jupiterbroadcasting.com/
  - type: dropdown
    id: devices
    attributes:
      label: On what type of device(s) did you see this bug?
      multiple: true
      options:
        - Phone
        - Tablet
        - Desktop
  - type: dropdown
    id: browsers
    attributes:
      label: On which browser(s) are you seeing the problem?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: input
    id: other_browser
    attributes:
      label: Other Browser
      description: If your browser is not in the list, enter it here.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Describe the bug you encountered.
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Contributing
      description: Please read our [Contributing Guidelines](https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/blob/main/CONTRIBUTING.md) before submitting an issue.
      options:
        - label: I have read through the [Contributing Guidelines](https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/blob/main/CONTRIBUTING.md)
          required: true
#         - label: I have read and accept the [Code of Conduct](https://docs.github.com/articles/github-community-guidelines)
#           required: true
