name: Website Bug Report
description: Found something weird on the website? Report it here
labels:
  - "bug"
  - "design"
body:
  - type: markdown
    attributes:
      value: |
        ### Thank you for reporting a bug! Please provide any information you think can help. Screenshots are a great help as well!
        ### Also please check to see if someone else has already reported this bug!
  - type: input
    id: address
    attributes:
      label: URL
      description: URL where the bug was found
      placeholder: https://jupiterbroadcasting.com/
  - type: dropdown
    id: devices
    attributes:
      label: What devices did you see this bug on?
      multiple: true
      options:
        - Phone
        - Tablet
        - Desktop
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Describe the bug you encountered
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Contributing
      description: Please read our [Contributing](https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/blob/main/CONTRIBUTING.md) Guidlines before submitting an issue.
      options:
        - label: I have read through the [Contributing](https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/blob/main/CONTRIBUTING.md) Guidlines
          required: true
#         - label: I have read and accept the [Code of Conduct](https://docs.github.com/articles/github-community-guidelines)
#           required: true
