name: Development
description: You are encountering an issue with the dev environment
labels:
  - "dev"
body:
  - type: markdown
    attributes:
      value: "## Please be as specific as possible so we can help you as best we can."
  - type: input
    attributes:
      label: Tools
      description: What tool(s) are affected?
      placeholder: Docker, GH Actions, etc.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Describe the issue you encountered. Feel free to throw in screenshots
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Guidlines
      description: We require everyone to read our [Contributing](https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/blob/main/CONTRIBUTING.md) Guidlines
      options:
        - label: I have read through the [Contributing](https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/blob/main/CONTRIBUTING.md) Guidlines
          required: true
#         - label: I have read and accept the [Code of Conduct](https://docs.github.com/articles/github-community-guidelines)
#           required: true
