name: Development
description: Issue encountered with our development enviornment
labels:
  - "dev"
body:
  - type: markdown
    attributes:
      value: |
        ## Please be as specific as possible. Thank you for your help supporting this project!
        ### Please check to see if someone else has already reported this bug!
  - type: input
    attributes:
      label: Tools
      description: What tool(s) are affected?
      placeholder: Docker, GH Actions, Make, etc.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Describe the issue you encountered. Feel free to throw in screenshots
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Contributing
      description: Please read our [Contributing](https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/blob/main/CONTRIBUTING.md) Guidlines before submitting an issue.
      options:
        - label: I have read through the [Contributing](https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/blob/main/CONTRIBUTING.md) Guidlines
          required: true
#         - label: I have read and accept the [Code of Conduct](https://docs.github.com/articles/github-community-guidelines)
#           required: true
