name: Feature Request
description: Suggest an idea to better the JB Website!
labels:
  - enchancement
body:
  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: Describe the feature you would like to see implemented
    validations:
      required: true
  - type: textarea
    id: reference
    attributes:
      label: Reference to Feature
      description: Have you seen this feature somewhere else?
  - type: checkboxes
    attributes:
      label: contributing
      description: We require everyone to read our [Contributing](https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/blob/main/CONTRIBUTING.md) Guidlines
      options:
        - label: I have read through the [Contributing](https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/blob/main/CONTRIBUTING.md) Guidlines
          required: true
#         - label: I have read and accept the [Code of Conduct](https://docs.github.com/articles/github-community-guidelines)
#           required: true
