name: Feature Request
description: Suggest an idea to better the JB Website!
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: "### Please check to see if someone else has already asked for this feature."
  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: Describe the feature you would like to see implemented.
    validations:
      required: true
  - type: textarea
    id: reference
    attributes:
      label: Reference to Feature
      description: Have you seen this feature somewhere else?
      placeholder: Please include links to references if you have them.
  - type: checkboxes
    attributes:
      label: Contributing
      description: Please read our [Contributing Guidelines](https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/blob/main/CONTRIBUTING.md) before submitting an issue.
      options:
        - label: I have read through the [Contributing Guidelines](https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/blob/main/CONTRIBUTING.md)
          required: true
#         - label: I have read and accept the [Code of Conduct](https://docs.github.com/articles/github-community-guidelines)
#           required: true
